/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface StaticImportMatch {
  bindings: string
  specifier: string
}
export declare function extractStaticImports(source: string): Array<StaticImportMatch>
